### ISSUE TITLE
Issue When attempting to install Velocity Report on a fresh Velocity Proxy

### ISSUE THREAD

**Issue by JosTheDude** [Syrent/VelocityReport#13]
Throwing this error:
```
[00:56:56 ERROR]: Couldn't pass ProxyInitializeEvent to velocityreport
java.lang.NoClassDefFoundError: org/bukkit/configuration/file/FileConfiguration
        at ir.syrent.velocityreport.spigot.storage.Settings.load(Settings.kt:35) ~[?:?]
        at ir.syrent.velocityreport.spigot.storage.Settings.<clinit>(Settings.kt:31) ~[?:?]
        at ir.syrent.velocityreport.VelocityReport.sendWarningMessage(VelocityReport.java:56) ~[?:?]
        at ir.syrent.velocityreport.VelocityReport.onProxyInitialization(VelocityReport.java:52) ~[?:?]
        at ir.syrent.velocityreport.Lmbda$15.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:47) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.configuration.file.FileConfiguration
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass0(PluginClassLoader.java:84) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at com.velocitypowered.proxy.plugin.PluginClassLoader.loadClass(PluginClassLoader.java:61) ~[server.jar:3.1.2-SNAPSHOT (git-7d77bfb5-b184)]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 11 more
```

However, the server is on Velocity (since it's showing a bukkit file configuration error) and the file is properly put into the Velocity plugins folder, config folders & file are not generating.

**Velocity Version**
```
[01:04:21 INFO]: Velocity 3.1.2-SNAPSHOT (git-7d77bfb5-b184)
[01:04:21 INFO]: Copyright 2018-2021 Velocity Contributors. Velocity is licensed under the terms of the GNU General Public License v3.
[01:04:21 INFO]: velocitypowered.com - GitHub
```

**Comment by Syrent** [comment]
Hi,
Just ignore this error for now. It shouldn't affect plugin logic and it should work.
Anyway, I try to fix this problem tomorrow.

**Comment by Syrent** [comment]
Try this version https://github.com/Syrent/VelocityReport/releases/tag/v2.2.0
