### ISSUE TITLE
Plugin is not working on 1.20.4 paper (build 378) and velocity 3.3.0 (build 316)

### ISSUE THREAD

**Issue by MrTroxy** [Syrent/VelocityReport#161]
### Server backend version

Paper 1.20.4 Build 378

### Server Velocity version

Velocity (1.20.4) 3.3.0-SNAPSHOT Build 316

### VelocityReport version

3.10.4

### Describe the bug

On this version, I can only manage to send report with commands and op players

If I just do /report <player>, the gui does not open and it just makes a sound

If I do /report <player> blocks automine for example this will work but only for op admins, normal players with the normal permission will get an internal error red message like this :
![image](https://github.com/Syrent/VelocityReport/assets/81443333/8532d844-d201-43a7-949c-8de6ba0f143a)

### Expected behavior

It's supposed to open the book GUI to choose report or not give an error when sending full command

### Steps to reproduce

Step 1 : /report <player>, will just give a sound and not open gui
Step 2 : /report <player> blocks automine (for example) will send an internal error if player isnt op

### Additional info

Before my server was running on velocity 1.20.2 and paper 1.20.2 and it was working

Here is the full console error it gives

> [14:56:23] [Server thread/INFO]: Bary issued server command: /report MrTroxy blocks automine
[14:56:23] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'report' in plugin VelocityReport v3.10.4
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.dispatchCommand(CraftServer.java:987) ~[paper-1.20.4.jar:git-Paper-378]
	at org.bukkit.craftbukkit.v1_20_R3.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.4.jar:git-Paper-378]
	at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.2.9.jar:?]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:32) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:19) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.commands.execution.CommandQueueEntry.a(CommandQueueEntry.java:5) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:101) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.commands.Commands.executeCommandInContext(Commands.java:435) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:336) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:323) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2234) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$16(ServerGamePacketListenerImpl.java:2194) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1458) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:194) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1435) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1358) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1336) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1220) ~[paper-1.20.4.jar:git-Paper-378]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-378]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NumberFormatException: For input string: "114468,43"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122) ~[?:?]
	at java.lang.Float.parseFloat(Float.java:476) ~[?:?]
	at ir.syrent.velocityreport.utils.ruom.utils.MilliCounter.get(MilliCounter.java:21) ~[VelocityReport.v3.10.4.jar:?]
	at ir.syrent.velocityreport.spigot.command.report.ReportCommand.onExecute(ReportCommand.kt:316) ~[VelocityReport.v3.10.4.jar:?]
	at ir.syrent.velocityreport.spigot.command.library.HandledCommand.handle(HandledCommand.kt:113) ~[VelocityReport.v3.10.4.jar:?]
	at ir.syrent.velocityreport.spigot.command.library.PluginCommand.onCommand(PluginCommand.kt:49) ~[VelocityReport.v3.10.4.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	... 29 more

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Fixed in latest snapshot
